name = "lapce-java"
version = "0.2.0"
author = "Paul Delafosse <paul.delfafosse@gmail.com>"
display-name = "Java"
description = "Lapce LSP plugin for java, powered by Eclipse JDT Language Server"
wasm = "bin/lapce-java.wasm"

[activation]
language = ["java"]
workspace-contains = ["*/*.java"]

[config."lombok"]
default = false
description = "Enable the lombok java agent"