name = "lapce-java"
version = "0.3.0"
author = "Paul Delafosse <paul.delfafosse@gmail.com>"
display-name = "Java"
description = "Lapce LSP plugin for java, powered by Eclipse JDT Language Server"
wasm = "bin/lapce-java.wasm"
icon = "JavaIcon.svg"
repository = "https://github.com/oknozor/lapce-java"

[activation]
language = ["java"]
workspace-contains = ["*/*.java"]

[config."lombok"]
default = false
description = "Enable the lombok java agent"

[config."volt.serverArgs"]
default = ""
description = "Language Server's Arguments"

[config."volt.serverPath"]
default = ""
description = "Path of `Java Language Server` executable. When empty, it points to the bundled binary `jdtls`."
